module.exports = {
  apps: [
    {
      name: "omniagent-server",
      script: "server/index.js",
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: { NODE_ENV: "development" },
      error_file: "logs/server-error.log",
      out_file: "logs/server-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "omniagent-collector",
      script: "collector/index.js",
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: { NODE_ENV: "development" },
      error_file: "logs/collector-error.log",
      out_file: "logs/collector-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "omniagent-frontend",
      script: "node_modules/vite/bin/vite.js",
      args: "--host",
      cwd: __dirname + "/frontend",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      error_file: "logs/frontend-error.log",
      out_file: "logs/frontend-out.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
