[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:server]
command=node /app/server/index.js
directory=/app/server
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:collector]
command=node /app/collector/index.js
directory=/app/collector
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
